### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by aforren1** [BLAM-Lab-Projects/finger-6#2]
- [x] Record absolute times only -- figure out relative times when needed
  - easier to document (what is relative to what is moot)
- [x] Drop relative presentation times in the timed response, do absolute times & convert to frames
  - Will stop consistently late presentation
- [x] TR object
  - Keyboard- or serial-based?
  - Starters exist for both
- [x] Add MRI experiment
- [x] ~~Add MRI vigilance type~~ Nixing for stronger data elsewhere
  - ~~Use hands as dummy stimuli~~
- [x] Find the 200ms chaff in TimedResp
- [x] Explicit go-nogo fMRI
- [x] Feedback in the scanner & better view for experimenters
  - [x] related: try getting multi-screen presentations right

Technical ToDo:
- [x] Replace numeric id with string based on tfile directory
- [x] Save data automatically (based on tfile name + directory + timestamp)
- [x] Save data on error and/or key combination (e.g. `esc`, which is already checked by TR class)
- [ ] Transition with black screen in the scanner (Nice-to-have) 
- [x] Timed response feedback based on peak force, not movement onset (makes feedback feel more natural)
- [x] Snappier free response feedback? It feels a bit mushy
- [x] Pre-generate files for 3 subjects
- [x] Feedback about peak force & push duration (post trial)
- [ ] calibrate?
- [x] Randomize initial training split of symbols independently of practice split of symbols
- [x] Seed generation of tgtfiles
- [x] Correctness feedback in the scanner? Quick 100-200ms flash on the push feedback would do

Design ToDo:
- [x] Finalize # of Training Blocks (2 split / 2 interleaved + top-up if below 95% accuracy)
- [x] Finalize # of TR Blocks after 1st scan (6 runs, 60/symbol) and time window (0.3 to 0.8) before last beep)
- [x] Finalize # of practice blocks per day (10 practice + 1 or 1/2 block non-practiced).
  - Possibly at a random time during practice
- [ ] Finalize switches ([1 3 5] or [2 4]?) Do we also switch non-practiced symbols? (Yes, but different fingers)
  - not same fingers for practiced/unpracticed
  - e.g. [2 4] vs [3 5](not the thumb). Counterbalance which ones are permuted in practice set.
- [x] Figure out exactly WHEN ForcedRT will be run
  - After initial training on Day 1
  - After scanning on Day 5
- [ ] Figure out how many switch-training trials prior to TR (200?)

**Comment by aforren1** [comment]
Updated list:
- [ ] Save data automatically (based on tfile name + directory)
- [ ] Save data on error and/or key combination (e.g. `esc`, which is already checked by TR class)
- [ ] Transition with black screen in the scanner (Nice-to-have) 
- [ ] Timed response feedback based on peak force, not movement onset (makes feedback feel more natural)
- [ ] Snappier free response feedback? It feels a bit mushy
- [ ] Pre-generate files for 3 subjects
- [ ] Feedback about peak force & push duration
- [ ] calibrate?

**Comment by aforren1** [comment]
Is it sufficient to seed at the top of `MakeAllTFiles`? I already seed `WriteTrTgt` and `WriteRtTgt` within their calls, which I would remove (it would mess with "randomness" anyway? All subjects end up with the same trial order)

**Comment by adrianhaith** [comment]
We definitely don't want all subjects to end up with the same trial order. So should seed based on their subject number.
